### ISSUE TITLE
Teste de funcionamento GNN

### ISSUE THREAD

**Issue by jorgealmeida1987** [ruipcosta/MTT#2]
O módulo GNN foi uma versão do MTT desenvolvida posteriormente mas que implementa o mesmo método do MTT normal.
O método implementado é Global Nearest Neighbour dai GNN.
Esta versão foi desenvolvida completamente em C++ o que marca um salto em relação à versão original do MTT.
Penso que seja proveitoso verificar se o GNN encontra-se a funcionar correctamente e eventualmente descartar a versão original do MTT em prol do GNN.

**Comment by ruipcosta** [comment]
GNN a funcionar!

**Comment by jorgealmeida1987** [comment]
Podes limpar ainda mais código do projecto.
Testa bem o GNN dentro do que precisas na tese e faz o ponto de situação amanha com o prof Vitor.

**Comment by ruipcosta** [comment]
Já consigo subscrever à informação dos alvos provenientes do gnn, no entanto tem de ser melhorado para me dar uma área do objeto detetado para conseguir fazer o cone de velocidade. Quanto ao código irei rever
