### ISSUE TITLE
Incluir informação morfológica nos targets

### ISSUE THREAD

**Issue by jorgealmeida1987** [ruipcosta/MTT#3]
A mensagem de alvo do GNN não inclui informação morfológica do mesmo.
![image](https://user-images.githubusercontent.com/25913513/76021949-1d182280-5f1e-11ea-82ea-7ec354d8bd2a.png)

Estude a melhor maneira de a incluir. 
Já não me recordo porque não está a ser incluída, não é um procedimento complicado.

**Comment by ruipcosta** [comment]
Adicionei a indicação do raio dos targets (distância do primeiro ponto ao centroid), no entanto este não atualiza, o que acaba por se tornar problemático se a deteção inicial não for a correta. O programa representa no rviz o circulo com esta informação. Para perceber se a informação esta correta, tambem é apresentado o circulo utilizando os dados detetados.
Será necessário mais alguma informação?

**Comment by jorgealmeida1987** [comment]
Apenas o raio parece-me informação insuficiente. Pode dar informação muito errada. 
Parece-me que basta que um alvo seja alongado, e haverá sempre uma percepção errada do seu verdadeiro tamanho.

![image](https://user-images.githubusercontent.com/25913513/76418026-d3a05b00-6395-11ea-8093-0ab07358f525.png)

**Comment by jorgealmeida1987** [comment]
Este issue está parado por algum motivo especial? precisas de mais orientações?

**Comment by ruipcosta** [comment]
Irei fazer o commit com as alterações efetuadas, no entanto apenas fiz a representação de linha entre todos os pontos. Confesso que estou a ter dificuldades em perceber quais informações adicionais são necessárias... Eu calculei o raio tambem para o velocity cone, que irei precisar. Acerca da imagem, através da mensagem já publicada é possivel verificar o ponto inicial e o ponto final. Poderei adicionar o comprimento do target, fazendo a distância entre estes pontos, mas para targets mal definidos (conjunto de pontos sem ordem aparente) este valor não teria significado. A informação de size apresentada na mensagem, não consegui detetar o que representa.

**Comment by ruipcosta** [comment]
O gnn não tem em conta a possibilidade do target aumentar ou diminuir de tamanho (não atualiza os pontos que o definem), isto tem alguma razão em específico? Quando o alvo muda de posição a informação de initialpose e finalpose fica desatualizada, bem como todos os seus pontos... 
![gnnbug](https://user-images.githubusercontent.com/58603032/77473283-23a70500-6e0d-11ea-9a0e-979d4e970a07.png)
